Add 05-tomcat8-maven-plugin module.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,6 +11,40 @@ env:
   JAVA_8_VERSION: '8'
   NODE_VERSION: '19.7.0'
 jobs:
+  tomcat8-maven-plugin:
+    if: github.event.inputs.trigger == ''
+      || !startsWith(github.event.inputs.trigger, 'm')
+      || !startsWith(github.event.inputs.trigger, 'M')
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
+        id: java-cache
+        with:
+          path: |
+            ./.n
+            ./.m2
+            ./build
+            ./.docker
+            ~/.m2/repository
+            !~/.m2/repository/io/github/daggerok
+          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: ${{ env.JAVA_8_VERSION }}
+      #- run: sudo apt install -yq curl
+      - run: test `command -v curl` || ( echo "curl command not found" ; false )
+      - run: |
+          nohup ./mvnw -f 05-tomcat8-maven-plugin clean package tomcat:run-war &
+          sleep 1s
+          retries=15
+          while [[ 0 -lt $retries ]] && [[ 200 -ne `curl -o /dev/null --silent --head --write-out "%{http_code} $LINE\n" 0:8080/05-tomcat8-maven-plugin/` ]] ; do
+            sleep 1s
+            echo -ne '.'
+            ((retries--))
+          done
+          curl -v 0:8080/05-tomcat8-maven-plugin/
   tomcat7-maven-plugin:
     if: github.event.inputs.trigger == ''
       || !startsWith(github.event.inputs.trigger, 'm')
